core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import UserLoginForm

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="core/login.html", authentication_form=UserLoginForm
        ),
        name="login",
    ),
    path("logout/", views.logout, name="logout"),
]

taskhub/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("tasks/", include("tasks.urls")),
]

tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.tasks, name="tasks"),
    path("create/", views.create_task, name="create_task"),
]

core/models.py
# Create your models here.

tasks/models.py
from django.contrib.auth.models import User
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    due_date = models.DateField(null=True, blank=True)
    assignee = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    completed = models.BooleanField(default=False)
    created_by = models.ForeignKey(
        User, related_name="created_by", on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class UserSignUpForm(UserCreationForm):
    class Meta:  # type: ignore
        model = User
        fields = ["username", "email", "password1", "password2"]

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your username",
                "class": "w-full p-2 my-2 border border-gray-300 rounded-sm",
            }
        )
    )

    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Your email address",
                "class": "w-full p-2 my-2 border border-gray-300 rounded-sm",
            }
        )
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Your password",
                "class": "w-full p-2 my-2 border border-gray-300 rounded-sm",
            }
        )
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Repeat password",
                "class": "w-full p-2 my-2 border border-gray-300 rounded-sm",
            }
        )
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not email.endswith("hs-fulda.de"):  # type: ignore
            raise ValidationError(
                "Only users with hs-fulda.de domain are allowed to register."
            )
        return email


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your username",
                "class": "w-full p-2 my-2 border border-gray-300 rounded-sm",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Your password",
                "class": "w-full p-2 my-2 border border-gray-300 rounded-sm",
            }
        )
    )

tasks/forms.py
from django import forms

from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:  # type: ignore
        model = Task
        fields = ["title", "description", "due_date", "assignee"]

core/views.py
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from .forms import UserSignUpForm


def index(request):
    return render(request, "core/index.html")


def signup(request):
    if request.method == "POST":
        form = UserSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("core:login")
    else:  # else is needed to render form on errors in POST
        form = UserSignUpForm()
    return render(request, "core/signup.html", {"form": form})


@login_required
def logout(request):
    auth_logout(request)
    return redirect("core:index")

tasks/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import redirect, render
from django.utils import timezone

from .forms import TaskForm
from .models import Task


def tasks(request):
    tasks = Task.objects.filter(
        Q(created_by=request.user) | Q(assignee=request.user)
    ).all()
    return render(request, "tasks/index.html", {"tasks": tasks})


@login_required
def create_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.created_by = request.user
            description = form.cleaned_data.get("description", "")
            new_task.description = (
                description if description else "No description provided."
            )
            if new_task.due_date < timezone.now().date():
                error_message = "Due date must be in the future."
                return render(
                    request,
                    "tasks/create_task.html",
                    {"form": form, "error_message": error_message},
                )
            new_task.save()
            return redirect("tasks:tasks")  # Redirect to the tasks page
    else:
        form = TaskForm()
    return render(request, "tasks/create_task.html", {"form": form})

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <title>{% block title %}{% endblock %} | Taskhub</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="bg-gray-100 text-gray-800 dark:bg-gray-950 dark:text-gray-100" hx-replace-url="true">
    <nav class="bg-gray-900 shadow-sm">
        <div class="max-w-screen-2xl mx-auto px-4 py-6 flex flex-wrap items-center justify-between">
            <h1 class="self-center font-semibold xl:text-xl text-lg text-gray-100 hover:text-gray-300 cursor-pointer">
                <a href="{% url 'core:index' %}">Taskhub</a>
            </h1>
            <button data-collapse-toggle="navbar-default" type="button"
                class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                aria-controls="navbar-default" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                    viewBox="0 0 17 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M1 1h15M1 7h15M1 13h15" />
                </svg>
            </button>
            <ul class="flex items-center space-x-6 text-gray-400 font-medium">
                {% if request.user.is_authenticated %}
                <li class="hover:text-gray-500"><a href="{% url 'tasks:tasks' %}">Tasks</a></li>
                <li class="text-sm px-6 py-3 font-medium bg-red-500 text-white hover:bg-red-700 rounded-sm">
                    <a href="{% url 'core:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="hover:text-gray-500"><a href="#">About</a></li>
                <li class="hover:text-gray-500"><a href="#">Contact</a></li>
                <li class="hover:text-gray-500">
                    <a href="{% url 'core:login' %}">Login</a>
                </li>
                <li>
                    <a class="px-4 py-2 bg-teal-700 text-white rounded hover:bg-teal-800"
                        href="{% url 'core:signup' %}">Sign Up</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="max-w-screen-2xl mx-auto px-4 py-6">
        <main>
            {% block body %}
            {% endblock %}
        </main>
    </div>

</body>

</html>

core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %}Home{% endblock %}

{% block body %}
<div class="p-4 gray-100 text-3xl max-w-4xl flex md:min-h-[30rem] items-center">
    <p>
        Taskhub is a task management app built in python to facilitate the creation, assignment and tracking of tasks
        within a collaborative environment.
    </p>
</div>
<a href="{% url 'core:signup' %}"
    class="m-4 p-4 text-gray-100 rounded-sm bg-teal-700 hover:bg-teal-900 font-semibold">Sign up Today</a>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}
{% block title %}Login{% endblock %}

{% block body %}
<div class="w-full max-w-xl mx-auto min-h-[40rem] mt-20 text-lg text-gray-800">
    <form action="." method="post" class="bg-white shadow-md rounded px-10 pt-6 pb-8 mb-4">
        {% csrf_token %}

        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
                Username
            </label>
            {{ form.username }}
        </div>

        <div class="mb-6">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="password">
                Password
            </label>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %}

        <div class="flex items-center justify-center">
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" type="submit">
                Login
            </button>
        </div>

    </form>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block body %}
<div class="w-full max-w-xl mx-auto min-h-[40rem] mt-20 text-lg text-gray-800">
    <form action="." method="post" class="bg-white shadow-md rounded px-10 pt-6 pb-8 mb-4">
        {% csrf_token %}

        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
                Username
            </label>
            {{ form.username }}
        </div>

        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="email">
                Email
            </label>
            {{ form.email }}
        </div>

        <div class="mb-6">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="password1">
                Password
            </label>
            {{ form.password1 }}
        </div>

        <div class="mb-6">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="password2">
                Repeat Password
            </label>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %}

        <div class="flex items-center justify-center">
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" type="submit">
                Sign Up
            </button>
        </div>

    </form>
</div>
{% endblock %}

tasks/templates/tasks/create_task.html
{% extends "core/base.html" %}

{% block title %}Tasks{% endblock %}

{% block body %}
<div class="p-4 gray-100 text-l max-w-4xl flex md:min-h-[30rem] items-center">
    <form method="post" action="">
        {% csrf_token %}
        {% if error_message %}
        <div class="alert alert-danger">{{ error_message }}</div>
        {% endif %}
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        {{ form.as_p }}
        <button type="submit"
            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Submit</button>
    </form>
</div>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "core/base.html" %}

{% block title %}Tasks{% endblock %}

{% block body %}
<div class="p-4 gray-100 max-w-4xl flex items-center">
    <p>
        Welcome to the Task Manager. This is a simple task manager that allows you to create, update, and delete tasks.
        You can also mark tasks as complete or incomplete. You can also filter tasks by their status.
    </p>
</div>
<div class="p-4">
    <h2 class="font-medium underline mb-4">Tasks:</h2>
    {% for task in tasks %}
    <div class="mb-2">
        {{task.title}}: {{task.description}} <br />
        Assigned to: {{task.assignee}} <br />
        Due date: {{task.due_date}}
    </div>
    {% endfor %}
</div>
<a class="m-4 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" href="{% url 'tasks:create_task' %}">Create New Task</a>
{% endblock %}